# TOML (Tom's Obvious, Minimal Language) format
[package]
name = "proj1_hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
